config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    resources :admins # Administradores
    resources :subjects # Assuntos/Áreas
    resources :questions # Questões
    delete 'admins/destroy/:id', to: 'admins#destroy'
    get 'welcome/index' # Dashboard
  end

  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'site/welcome#index'
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  has_many :questions

  validates :description, presence: true, uniqueness: true
end

app/controllers/admins_backoffice/admins_controller.rb
# frozen_string_literal: true

module AdminsBackoffice
  class AdminsController < AdminsBackofficeController
    before_action :verify_password, only: %i[update]
    before_action :set_admin, only: %i[show edit update destroy]

    def index
      @admins = Admin.all.page(params[:page]).per(10)
    end

    def new
      @admin = Admin.new
    end

    def create
      @admin = Admin.create(params_admin)
      if @admin.save
        redirect_to admins_backoffice_admins_path, notice: 'Admin cadastrado com sucesso.'        
      else
        render :new, status: :unprocessable_entity        
      end
    end

    def show; end

    def edit; end

    def update
      if @admin.update(params_admin)
        redirect_to admins_backoffice_admins_path, notice: 'Admin atualizado com sucesso.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @admin.destroy
        redirect_to admins_backoffice_admins_path, notice: 'Admin excluído com sucesso.', status: :see_other
    end

    private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      params.require(:admin).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def verify_password
      return unless params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?

      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
# frozen_string_literal: true

module AdminsBackoffice
  class QuestionsController < AdminsBackofficeController
    before_action :set_question, only: %i[show edit update destroy]
    before_action :get_subjects, only: %i[new edit]

    def index
      @questions = Question.all.includes(:subject).order(:description).page(params[:page]).per(10)
    end

    def new
      @question = Question.new
    end

    def create
      @question = Question.new(params_question)
      if @question.save
        redirect_to admins_backoffice_questions_path, notice: 'Questão cadastrada com sucesso.', status: :see_other
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      if @question.update(params_question)
        redirect_to admins_backoffice_questions_path, notice: 'Questão atualizada com sucesso.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @question.destroy
      redirect_to admins_backoffice_questions_path, notice: 'Questão deletada com sucesso'
    end

    private

    def set_question
      @question = Question.find(params[:id])
    end

    def params_question
      params.require(:question).permit(:subject_id, :description,
                                       answers_attributes: %i[id description correct _destroy])
    end

    def get_subjects
      @subjects = Subject.all
    end
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
# frozen_string_literal: true

module AdminsBackoffice
  class SubjectsController < AdminsBackofficeController
    before_action :set_subject, only: %i[show edit update destroy]

    def index
      @subjects = Subject.all.page(params[:page]).per(10)
    end

    def new
      @subject = Subject.new
    end

    def create
      @subject = Subject.new(params_subject)
      if @subject.save
        redirect_to admins_backoffice_subjects_path, notice: 'Assunto cadastrado com sucesso.', status: :see_other
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      if @subject.update(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: 'Assunto atualizado com sucesso.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @subject.destroy
      redirect_to admins_backoffice_subject_path, notice: 'Assunto atualizado com sucesso.'
    end

    private

    def set_subject
      @subject = Subject.find(params[:id])
    end

    def params_subject
      params.require(:subject).permit(:description)
    end
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
# frozen_string_literal: true

module AdminsBackoffice
  class WelcomeController < AdminsBackofficeController
    def index; end
  end
end

app/controllers/admins_backoffice_controller.rb
# frozen_string_literal: true

class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
# frozen_string_literal: true

module AdminsBackoffice
  module AdminsHelper
    def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
  end
end

app/helpers/admins_backoffice/questions_helper.rb
# frozen_string_literal: true

module AdminsBackoffice
  module QuestionsHelper
  end
end

app/helpers/admins_backoffice/subjects_helper.rb
# frozen_string_literal: true

module AdminsBackoffice
  module SubjectsHelper
  end
end

app/helpers/admins_backoffice/welcome_helper.rb
# frozen_string_literal: true

module AdminsBackoffice
  module WelcomeHelper
  end
end

app/helpers/admins_backoffice_helper.rb
# frozen_string_literal: true

module AdminsBackofficeHelper
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: 'Editando'} %>

app/views/admins_backoffice/subjects/index.html.erb
<h1>Listando Assuntos/Áreas</h1>

 <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Descrição</th>                
                <th><%= link_to new_admins_backoffice_subject_path, class: "btn-sm btn-success btn-circle" do %>
                    <i class="fas fa-plus"></i></th>  
                    <% end %>
                                
            </tr>
        </thead>
        
        <tbody>
            <% @subjects.each do |subject| %>
            <tr>             
                <td><%= subject.description %></td>              
                <td style="width: 120px"> 
                  <%= link_to admins_backoffice_subject_path(subject), class: "btn-sm btn-primary btn-circle" do %>
                    <i class="fas fa-user"></i>
                  <% end %>
                  <%= link_to edit_admins_backoffice_subject_path(subject), class: "btn-sm btn-secondary btn-circle" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to admins_backoffice_subject_path(subject), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn-sm btn-danger btn-circle" do %>
                    <i class="fas fa-trash"></i>
                  <% end %>                  
                </td>               
            </tr>
            <% end %>
                
        </tbody>
    </table>
    
    <%= paginate @subjects %>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: 'Criando'} %>

app/views/admins_backoffice/subjects/show.html.erb
<h1>Listando Administradores</h1>

 <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Descrição</th>                              
            </tr>
        </thead>
        
        <tbody>                
                <td><%= @subject.description %></td>      
        </tbody>
    </table>
</div>